### ISSUE TITLE
Should menu items be alphabetized?

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/cirdles.github.com#58]
Looking over the site today, I noticed that all of the menus were in alphabetical order. This didn't entirely make sense to me. For example, under "Projects", I wanted to see ET_Redux listed first because it's the flagship product, not third. Under "About", I thought that "People" should've been above "Collaborators", if only because it has more engaging content.

@bowring and @Jmack2, what are your thoughts? Maybe we could come to a consensus on a better ordering for each of the menus.

**Comment by bowring** [comment]
Great ideas - I have not had time to review the site as I had not
anticipated needing it quite so soon.  Have at it.

On Sun, Nov 8, 2015 at 12:34 PM, John Zeringue <notifications@github.com>
wrote:

> Looking over the site today, I noticed that all of the menus were in
> alphabetical order. This didn't entirely make sense to me. For example,
> under "Projects", I wanted to see ET_Redux listed first because it's the
> flagship product, not third. Under "About", I thought that "People"
> should've been above "Collaborators", if only because it has more engaging
> content.
>
> @bowring <https://github.com/bowring> and @Jmack2
> <https://github.com/Jmack2>, what are your thoughts? Maybe we could come
> to a consensus on a better ordering for each of the menus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/cirdles.github.com/issues/58>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.

**Comment by Jmack2** [comment]
@johnzeringue I also think it is a great idea. I am currently trying to change the order of the menus to importance rather than alphabetized.

**Comment by baldwinjj** [comment]
There is a new file _data/main-menu.yml that allows you to specify the order of the menu
