### ISSUE TITLE
Add Gitter sidecar

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/cirdles.github.com#60]
Not sure if it's a good idea or not, but there is a new Gitter feature that allows you embed a sidecar in your own websites (see [here](https://sidecar.gitter.im)). This would allow us to have the CIRDLES Gitter chat available directly from cirdles.org. Thoughts?

**Comment by bowring** [comment]
let's try it for Topsoil

On Sun, Nov 8, 2015 at 9:51 PM, John Zeringue <notifications@github.com>
wrote:

> Not sure if it's a good idea or not, but there is a new Gitter feature
> that allows you embed a sidecar in your own websites (see here
> <https://sidecar.gitter.im>). This would allow us to have the CIRDLES
> Gitter chat available directly from cirdles.org. Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CIRDLES/cirdles.github.com/issues/60>.
>



-- 
Jim Bowring
C. Richard Crosby Distinguished Teaching Co-Chair
Principal Investigator, www.CIRDLES.org, www.github.com/cirdles

Computer Science
College of Charleston
66 George Street
Charleston, SC 29424

Google Voice: 843.608.1399 (preferred)
Google Email: bowring@gmail.com

Office:
Harbor Walk East (360 Concord Street) Room 308
843.953.0805
http://stono.cs.cofc.edu/~bowring/
bowringj@cofc.edu

R. Buckminster Fuller (1972):
If humanity is to survive aboard our planet, it must become universally
literate and preoccupied with inherently cooperative Comprehensive
Anticipatory Design Science in which every human is concerned with
accomplishing the comfortably sustainable well-faring of all other humans.
