### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by johnzeringue** [CIRDLES/cirdles.github.com#67]
Running `htmlproof --href-ignore '#' --alt-ignore '/.*/' _site` (a command checking for broken links) after generating the site locally produces the following output:

```
- _site/about/news/1999/11/29/updates.html
  *  External link http://cirdles.org/about/news/1999/11/29/updates.html failed: 404 No error
- _site/about/news/2008/04/12/welcome-on-cirdles-blog.html
  *  External link http://cirdles.cs.cofc.edu/ failed: got a time out
  *  External link http://cirdles.cs.cofc.edu/wiki failed: got a time out
- _site/about/news/2008/06/20/u-pbredux-uml-study.html
  *  External link http://cirdles.cs.cofc.edu/wiki/pmwiki.php?n=Main.Documentation failed: got a time out
- _site/about/news/2014/10/11/nsf-award.html
  *  External link http://www.cs.cofc.edu/blog/2014/10/college-professor-awarded-part-of-nsfs-31-million-to-improve-big-data/ failed: 500 No error
- _site/about/publications/index.html
  *  External link http://home.segal.uvic.ca/~IRCoSE-2008/irecose2008_8.pdf failed: got a time out
- _site/community/u-series/index.html
  *  External link http://www.nature.com/nature/journal/v437/n7058/full/nature03993.html failed: 401 No error
- _site/projects/chroni/index.html
  *  anchor has no href attribute (line 641)
- _site/projects/et_redux/index.html
  *  External link http://cirdles.org/sites/default/files/Downloads/ggge1932.pdf failed: 404 No error
  *  External link http://cirdles.org/sites/default/files/Downloads/ggge1933.pdf failed: 404 No error
- _site/resources/synthetic-data/index.html
  *  internally linking to ../assets/documents/U-Pb_Redux_Demo.pdf, which does not exist (line 567)
  *  internally linking to ../assets/downloads/cm1.zip, which does not exist (line 569)
  *  internally linking to ../assets/downloads/cm2.zip, which does not exist (line 571)
htmlproof 2.5.2 | Error:  HTML-Proofer found 13 failures!
```

Of these:
- The first seems to be a date issue. I was able to fix it locally by removing the time (`01:00:00`) from that post's [front matter](http://jekyllrb.com/docs/frontmatter/).
- The next 3 seem to be resolvable after getting `cirdles.cs.cofc.edu` to be an alias for `cirdles.org`. With that, we can create appropriate [redirects](https://help.github.com/articles/redirects-on-github-pages/).
- The next 2 might be lost to time.
- The next one is fine, the page loads normally with a 401 status because it's a paywall.
- The one after that is a typo in [`_chroni/test2.md`](https://github.com/CIRDLES/cirdles.github.com/blob/master/_chroni/test2.md).
- The final five are missing assets (PDFs and ZIPs) that used to be hosted by the Drupal site.

I think it's best to resolve this issue in a pull request that includes adding a Travis build with `htmlproof`, like I've done on [my blog](https://github.com/johnzeringue/johnzeringue.github.com). However, this depends on #66, so we can wait a day or two.

In the meantime, it would be good to address the following:
- [x] Get an `ALIAS` entry for `cirdles.cs.cofc.edu` pointing to `cirdles.org`.
- [x] See if we can dig up the `home.segal.uvic.ca` link.
- [ ] Locate the missing assets.

@bowring, unfortunately, I think they all involve you, unless @Jmack2 has a copy of the Drupal site to extract the assets.

I think it should also be said that I think it's best to try and restore as many of these links as we can. Even if we plan to change them within our site, we never know where they might be used. The goal for all of our new GitHub-centered infrastructure is to have the reliability and redundancy that our old infrastructure didn't.

Lastly, kudos to @baldwinjj and @Jmack2! Although the new site ended up being a preemie due to the Drupal site falling off the map, the switchover's been remarkably smooth. It's pretty impressive that we've only ended up with a few broken links, many of which were out of our control. It looks great, guys! :smile:

**Comment by bowring** [comment]
@Jmack2 - See me for an in person review of how to solve these link problems.

**Comment by Jmack2** [comment]
@bowring I will definitely meet with you. Would you want to meet on Wednesday as usual or would you like to meet earlier?

**Comment by bowring** [comment]
@Jmack2 - what is your schedule this afternoon?

**Comment by Jmack2** [comment]
@bowring  I know I would be at Harbor Walk at 12:00pm today.

**Comment by johnzeringue** [comment]
While improvements have been made, running the tool still finds some problems:

```
$ htmlproof --href-ignore '#' --alt-ignore '/.*/' _site
`@options[:href_ignore]` will be renamed in a future 3.x.x release: http://git.io/vGHHy
Running ["ScriptCheck", "LinkCheck", "ImageCheck"] checks on _site on *.html... 


Checking 127 external links...
Ran on 31 files!


- _site/community/u-series/index.html
  *  External link http://www.nature.com/nature/journal/v437/n7058/full/nature03993.html failed: 401 No error
- _site/projects/chroni/index.html
  *  anchor has no href attribute (line 691)
- _site/resources/synthetic-data/index.html
  *  internally linking to ../assets/documents/U-Pb_Redux_Demo.pdf, which does not exist (line 610)
  *  internally linking to ../assets/downloads/cm1.zip, which does not exist (line 612)
  *  internally linking to ../assets/downloads/cm2.zip, which does not exist (line 614)
htmlproof 2.5.2 | Error:  HTML-Proofer found 5 failures!
```

This should be fixed with the inclusion of Travis so that we're not manually sniffing out broken links. As the site grows, we're going to have to depend on tooling.

**Comment by Jmack2** [comment]
@bowring I have emailed the IT department about getting the alias for cirdles.org. They will probably email back the week when students come back from break. I also cc'd you on the email.

**Comment by Jmack2** [comment]
- _site/community/u-series/index.html
    -I was able to successfully load up each of the links, but some articles required registration/login access.
Still working on the other issues

**Comment by johnzeringue** [comment]
@Jmack2, yeah, the 401 seems fine. We can ask the tool to ignore it later.

**Comment by Jmack2** [comment]
This issue will be closed and any missing assets will be found down the road. As of right now, links seem to all work.
